services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - scheduler-network
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - scheduler-network

networks:
  scheduler-network:
    driver: bridge

